### ISSUE TITLE
Don't install if the required packages already exist in the PATH

### ISSUE THREAD

**Issue by Weissle** [jayp0521/mason-null-ls.nvim#17]
I have stylua in my system. But `mason-null-ls.nvim` still install stylua through mason.
I know I can prohibit it from installing stylua by changing the config.
But I wonder if there is a smarter way that is suitable for all packages.

**Comment by jayp0521** [comment]
https://github.com/jayp0521/mason-null-ls.nvim/blob/main/lua/mason-null-ls/settings.lua#L16

```lua
automatic_installation = { exclude = { "stylua", } }
```

you can do it like this. This feature should be controlled by `mason.nvim` not this plugin. If `mason.nvim` decides to not do duplicate installs, it will be supported.
