### ISSUE TITLE
unknown source error on setting up handlers

### ISSUE THREAD

**Issue by elspecal** [jayp0521/mason-null-ls.nvim#18]
```
[mason.nvim] mason-null-ls.setup_handlers: Received handler for unknown null-ls source name: beautysh.
[mason.nvim] mason-null-ls.setup_handlers: Received handler for unknown null-ls source name: zsh.
```
i get the above error messages on startup. relevant parts of my config:

mason-null-ls.lua:

```lua
local ok, mnl = pcall(require, "mason-null-ls")
if not ok then
    print("failed to load mason-null-ls")
    return
end

mnl.setup({
    automatic_installation = true,
    ensure_installed = { "beautysh", "zsh" },
})

local nullls = require("null-ls")

mnl.setup_handlers({
    function(source_name) end,
    beautysh = function()
        nullls.register(nullls.builtins.diagnostics.beautysh)
    end,
    zsh = function()
        nullls.register(nullls.builtins.formatting.zsh)
    end,
})

nullls.setup()
```

lua/miki/plugins.lua:

```lua
    -- package manager
    {
      "williamboman/mason.nvim",
      config = "require 'miki.configs.mason'",
    },
    {
      "williamboman/mason-lspconfig.nvim",
      after = "mason.nvim",
      config = "require 'miki.configs.mason-lspconf'",
    },
    {
      "jayp0521/mason-null-ls.nvim",
      config = "require 'miki.configs.mason-null-ls'",
      after = "null-ls.nvim",
    },
```

i'm on `NVIM v0.9.0-dev-16-g56998feeb`. the plugin has been working fine so far otherwise. what do i do wrong?

**Comment by KaziSadmanAhmed** [comment]
These packages are not available in the mason registry. You can check at https://github.com/williamboman/mason.nvim/blob/main/PACKAGES.md

You need install the packages yourself until someone adds those to the registry.

**Comment by elspecal** [comment]
oh i see. too bad. can you give me guidance how to add a new package to the registry?

**Comment by KaziSadmanAhmed** [comment]
> oh i see. too bad. can you give me guidance how to add a new package to the registry?

You can find the official guide here: https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md#adding-a-new-package

For reference: https://github.com/williamboman/mason.nvim/pull/523

**Comment by jayp0521** [comment]
Thanks sending that over! Hope it helps. Closing this issue

**Comment by jayp0521** [comment]
https://github.com/williamboman/mason.nvim/pull/525/files

Example PR for pip packages

**Comment by jayp0521** [comment]
https://github.com/williamboman/mason.nvim/pull/526

PR to add `beautysh`
