### ISSUE TITLE
Contradictory documentation

### ISSUE THREAD

**Issue by marcusatiliusregulus** [jayp0521/mason-null-ls.nvim#34]
The README.md section "Setup" reminds to make sure the setup functions are called in this exact order: 1. mason 2. null-ls 3. mason-null-ls.
However, the section "Setup handlers usage" gives an example in which null-ls's setup is called *after* mason-null-ls's setup.

**Comment by jayp0521** [comment]
Hello,

Yeah I've noticed this. Unless you're using `automatic_setup`, the order shouldn't matter. `automatic_setup` requires null_ls to be loaded and set up first. I will update the docs to reflect this something next week when I'm back home or feel free to open a PR. I'm not good at writing/maintaining docs :)

**Comment by jayp0521** [comment]
https://github.com/jayp0521/mason-null-ls.nvim/tree/docs

should be fixed in
