### ISSUE TITLE
Exclude list of tools from automatic installation

### ISSUE THREAD

**Issue by ghassan0** [jayp0521/mason-null-ls.nvim#6]
It would be really helpful to be able to exclude some tools from automatically installing. Unfortunately, Mason is unable to install some tools on some platforms such as Termux(Android) and FreeBSD/OpenBSD but it would be really nice to still take advantage of this plugin to automatically install the majority of compatible plugins. 

It would look like `mason-lspconfig.nvim` implementation of this feature:
```
    -- Whether servers that are set up (via lspconfig) should be automatically installed if they're not already installed.
    -- This setting has no relation with the `ensure_installed` setting.
    -- Can either be:
    --   - false: Servers are not automatically installed.
    --   - true: All servers set up via lspconfig are automatically installed.
    --   - { exclude: string[] }: All servers set up via lspconfig, except the ones provided in the list, are automatically installed.
    --       Example: automatic_installation = { exclude = { "rust_analyzer", "solargraph" } }
    automatic_installation = false,
```

**Comment by jayp0521** [comment]
https://github.com/jayp0521/mason-null-ls.nvim/pull/10

added in
